name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Publish Blazor project to the release-folder
      run: dotnet publish test-site.csproj -c Release -o release --nologo
    - name: Committ wwwroot to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
